### ISSUE TITLE
Markdown-flavor syntax?

### ISSUE THREAD

**Issue by todrobbins** [inkandswitch/pushpin#181]
Is any kind of Markdown-flavor syntax on the roadmap? Or a WYSIWYG, maybe http://substance.io/?

Cheers!

**Comment by pvh** [comment]
We had markdown support early in the project but removed it because we couldn't find a good wysiwyg experience for it. If you can find an open-source implementation in another project that you like I'll certainly consider it.

**Comment by todrobbins** [comment]
Maybe https://ui.toast.com/tui-editor/?
