### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by erangell** [inkandswitch/pushpin#187]
Did git clone today and npm install:

npm WARN engine xmlbuilder@9.0.7: wanted: {"node":">=4.0"} (current: {"node":"0.12.2","npm":"2.7.5"})

> electron-forge@5.2.2 install /Users/ericrangell/git/pushpin/node_modules/electron-forge
> node tabtab-install.js

/Users/ericrangell/git/pushpin/node_modules/electron-forge/tabtab-install.js:9
  let shell = process.env.SHELL;
      ^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Darwin 16.7.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! electron-forge@5.2.2 install: `node tabtab-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-forge@5.2.2 install script 'node tabtab-install.js'.
npm ERR! This is most likely a problem with the electron-forge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tabtab-install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-forge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ericrangell/git/pushpin/npm-debug.log
Erics-MacBook-Pro:pushpin ericrangell$ 

[npm-debug.log](https://github.com/inkandswitch/pushpin/files/2435147/npm-debug.log)

**Comment by erangell** [comment]
Same error happens when downloading ZIP source for the Release.
Probably is an issue with Electron 3 breaking previous dependencies.

**Comment by erangell** [comment]
I was able to npm install and npm start Pushpin on a Raspberry Pi today.  If people are still experiencing issues they may need to retry with a clean environment - the node dependencies are constantly evolving.

**Comment by pvh** [comment]
I've moved us over to yarn and upgraded all the dependencies. Things will work, well, differently at least now!
