### ISSUE TITLE
Card content divergence (intermittent)

### ISSUE THREAD

**Issue by HerbCaudill** [inkandswitch/pushpin#188]
![pushpin-screen-capture-2018-11-30_14-59-17](https://user-images.githubusercontent.com/2136620/49295542-4db91300-f4b6-11e8-84d4-63aa9c3f804c.gif)

I haven't found a way to reproduce this consistently, but it happens frequently. As this screen capture shows, it starts with a card on a shared board showing up empty, even though it has content on the original board. From that point, the text of the card can be updated any number of times on either side without the text converging. 

Reloading the incorrect instance straightens it out.

**Comment by pvh** [comment]
Hi @HerbCaudill! I'm going to close this issue because I've now completely replaced the Hypermerge implementation with a newer one and while I'm sure there are NEW bugs (please report them) this one is now unlikely to have the same cause or solution.
