### ISSUE TITLE
try discovery-swarm-web

### ISSUE THREAD

**Issue by pvh** [inkandswitch/pushpin#193]
The P2P data connections in discovery-swarm have somehow become less reliable to the point where pushpin no longer consistently connects even within the same computer (for me). I've swapped in our websocket echo server implementation (discovery-cloud-client) which talks to a Heroku backend to broker connections. This is a fine short-term solution but I'd be much happer working with, say, @rangermauve to figure out why this is happening and restoring the functionality.

**Comment by RangerMauve** [comment]
Sorry, to clarify, is the problem with discovery-swarm-web or discovery swarm? 😅

**Comment by RangerMauve** [comment]
Actually, this might be a great opportunity to live life on the edge and try out hyperswarm. 😀

**Comment by pvh** [comment]
@RangerMauve this is discovery-swarm and I've moved over to discovery-cloud-client which is our version of discovery-swarm-web that predates yours :)

**Comment by pvh** [comment]
I left a couple bug reports on discovery-swarm-web, but it didn't work for me so I'm going to close this out until/unless @RangerMauve wants to work with me on it since our current solution is not blocking other work.
