### ISSUE TITLE
[upgrade] deprecated crypto warnings

### ISSUE THREAD

**Issue by pvh** [inkandswitch/pushpin#195]
Haven't tracked these down and probably should. Hopefully it isn't some new Trojan horse?

**Comment by canadaduane** [comment]
After some hunting, I found a way to turn on tracing for deprecation warnings in electron: just add the following to top of `src/main/index.js` (after the `import`s):
```
process.traceDeprecation = true
process.traceProcessWarnings = true
```

Doing so uncovered the source of the crypto warnings:

```
  (node:73964) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
      at __importStar (/Users/dujohnson/tmp/pushpin/node_modules/discovery-cloud-client/dist/WebSocketStream.js:8:96)
      at Object.<anonymous> (/Users/dujohnson/tmp/pushpin/node_modules/discovery-cloud-client/src/WebSocketStream.ts:3:1)
      at Object.<anonymous> (/Users/dujohnson/tmp/pushpin/node_modules/discovery-cloud-client/dist/WebSocketStream.js:70:3)
```

**Comment by canadaduane** [comment]
Looks like @jeffpeterson has already removed the crypto library from `discovery-cloud-client`, but the `0.0.3` version hasn't made its way to npm yet: https://github.com/inkandswitch/discovery-cloud-client/commit/45a4b1a579496c8109280bae118bb1d6d8112ce1

**Comment by canadaduane** [comment]
Tested and confirmed that replacing `"0.0.1"` with `"github:inkandswitch/discovery-cloud-client"` in `package.json` fixes the warnings.

**Comment by pvh** [comment]
Fixed with a newer release.
