### ISSUE TITLE
Convert to Typescript

### ISSUE THREAD

**Issue by mjtognetti** [inkandswitch/pushpin#211]
Typescripts provides a lot of nice benefits. In particular, explicitly defining document shapes will be useful for comprehension and maintenance.

We can convert the entire codebase in a single pass. Will take an hour or two. 

In addition to converting the actual JS files, we'll need to either remove eslint or convert it to use the typescript parser and linting rules.

I advocate for replacing eslint with prettier. Prettier not only ensures consistent styling across the codebase but also saves time and effort.

**Comment by mjtognetti** [comment]
We can do this after #203 is merged. If progress is being made on #86 could also wait for that - or I can convert to ts in-branch.

**Comment by pvh** [comment]
Done!
