### ISSUE TITLE
horizontally squished avatar in the TitleBar

### ISSUE THREAD

**Issue by todrobbins** [inkandswitch/pushpin#224]
![Screen Shot 2019-06-24 at 11 45 36 AM](https://user-images.githubusercontent.com/158590/60040235-bc89d380-9675-11e9-8336-8fd454b151a9.png)

Not sure what's causing this, but when I change the value or toggle `.Avatar--title-bar` in devtools the aspect ratio is corrected. 🤷🏻‍♂️

Also, looks correct in `Your Profile`:

![Screen Shot 2019-06-24 at 11 47 15 AM](https://user-images.githubusercontent.com/158590/60040355-07a3e680-9676-11e9-9ceb-6178532a6af5.png)

**Comment by pvh** [comment]
I believe this is now fixed!
