### ISSUE TITLE
Board icon isn't transparent when dragging

### ISSUE THREAD

**Issue by todrobbins** [inkandswitch/pushpin#367]
Minor UI bug: there is a white background when you click-and-drag the board icon. The background should be transparent IMO ✌🏻

<img width="744" alt="Screen Shot 2019-12-16 at 11 13 34 AM" src="https://user-images.githubusercontent.com/158590/70942864-d563b800-200c-11ea-90e9-b4aabd192e17.png">

**Comment by pvh** [comment]
fixed on master
